### ISSUE TITLE
Black screen after resuming from suspension

### ISSUE THREAD

**Issue by ghost** [d0k3/CTRXplorer#10] opened 2016-01-21 20:29 UTC
The latest .cia version of CTRXplorer will show a black, unresponsive screen after being resumed from suspension. I'm using a New 3DS.

**Comment by d0k3** [comment] 2016-01-22 11:56
I just tried this (CIA with N3DS EmuNAND 10.4 & 3DSX on N3DS SysNAND 9.0). Could not reproduce this problem - suspending and waking up worked without trouble. Can you give me some information? Does it work with other homebrew for you? You could, f.e. try FBI.

**Comment by ghost** [comment] 2016-01-22 20:04
N3DS 10.3U EmuNAND also doesn't work on 10.4U
Other homebrew like ftp-3ds and fbi works.

**Comment by ghost** [comment] 2016-01-22 20:04
I'm using cakes fw btw

**Comment by d0k3** [comment] 2016-01-23 12:52
Well, no idea yet. I'll migrate the CTRXplorer to the newer citrus library, then ask you to try again.

**Comment by d0k3** [comment] 2016-01-24 13:41
Alright, completely rebased on citrus. Could you try again? If possible, it may also make sense for you to try it in homebrew launcher.

**Comment by ghost** [comment] 2016-01-27 04:24
Tryed it again. Still doesn't work sadly :/ (Sorry for the delay, I bricked my emuNAND xD) And I don't really understand what you mean by trying it in the hb launcher, I can't suspend software there..

**Comment by d0k3** [comment] 2016-01-27 09:45
Homebrew Launcher allows suspending, at least in *hax 2.5. It somewhat seems that this is not a full suspend, though.

Now, can you try to give me some more details? You're closing the lid then opening it again? Or do you mean pressing the home button to return to home menu, then returning from there?

**Comment by ghost** [comment] 2016-01-27 19:03
Pressing the home menu button and returning from thete

**Comment by ghost** [comment] 2016-01-27 19:03
There*

**Comment by ghost** [comment] 2016-01-27 19:04
I have a video but I don't know where to upload it..

**Comment by d0k3** [comment] 2016-01-27 19:27
Suspending with the homebutton also causes no trouble for me. For the video... Youtube? You might not want that because anonymity. Use [this](https://vid.me/) or [this](https://sendvid.com/)

**Comment by d0k3** [comment] 2016-05-05 16:15
Is this still an issue, @s3r1alpari4h ?

**Comment by d0k3** [comment] 2016-05-24 12:50
Okay, closing this now, because this was not reproducable. If this is still an issue, feel free to reopen it!

**Closed as completed by d0k3** 2016-05-24 12:50 UTC
Labels: bug

**Comment by ghost** [comment] 2016-06-10 15:38
Oh very sorry I haven't gotten back to you sooner, it seems to be my particular system because it works on my other one.

**Comment by v0idst4r** [comment] 2016-07-26 06:54
Eh sorry I never got back it was still an issue on the version I opened it on bit it's not an issue on the latest version (0.9. 7) so I'll keep it closed

**Comment by v0idst4r** [comment] 2016-07-26 06:55
"ghost" was my old account
